fix(precommit): clean create-release shellcheck

diff --git a/files/home/.local/bin/create-release b/files/home/.local/bin/create-release
--- a/files/home/.local/bin/create-release
+++ b/files/home/.local/bin/create-release
@@ -1,25 +1,20 @@
 #!/usr/bin/env bash
 
 if ! git diff --quiet; then
-	echo "Commit local changes before making a release"
-	exit 1
+  echo "Commit local changes before making a release"
+  exit 1
 fi
 
-IMAGE_TAG=$(git describe --tags --abbrev=0)
-
-if [ $? -ne 0 ]; then
-	echo "No tag specified and no git repository"
-	exit 1
+if ! IMAGE_TAG=$(git describe --tags --abbrev=0); then
+  echo "No tag specified and no git repository"
+  exit 1
 fi
 
-IMAGE_TAG="v$(semver -i "${IMAGE_TAG}")"
-
-if [ $? -ne 0 ]; then
-	echo "Could not increment version"
+if ! IMAGE_TAG="v$(semver -i "$IMAGE_TAG")"; then
+  echo "Could not increment version"
+  exit 1
 fi
 
-create-registry-image --push --version "$IMAGE_TAG" "$@"
-
-if [ $? -eq 0 ]; then
-	git tag "$IMAGE_TAG"
+if create-registry-image --push --version "$IMAGE_TAG" "$@"; then
+  git tag "$IMAGE_TAG"
 fi
