fix: gpg agent pinentry, macos fortunes, byobu config, ansible vault pass, bootstrap
more fixes to do with h fzf and locale on macos

diff --git a/collections/ansible_collections/ryjen/dotfiles/roles/ansible/files/dotfiles/.local/bin/ansible-vault-pass b/collections/ansible_collections/ryjen/dotfiles/roles/ansible/files/dotfiles/.local/bin/ansible-vault-pass
--- a/collections/ansible_collections/ryjen/dotfiles/roles/ansible/files/dotfiles/.local/bin/ansible-vault-pass
+++ b/collections/ansible_collections/ryjen/dotfiles/roles/ansible/files/dotfiles/.local/bin/ansible-vault-pass
@@ -1,3 +1,11 @@
 #!/usr/bin/env sh
 
-pass show ansible-vault-pass
+if ! type pass 2>&1 1>/dev/null; then
+	echo "UNIX pass command not installed, manual password required." >&2
+	exit 1
+fi
+
+if ! pass show ansible-vault-password 2>/dev/null; then
+	echo "UNIX pass command failed, manual password required." >&2
+	exit 1
+fi
